version: "3.9"

services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=dispatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - WAL_LEVEL=logical
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  pg_data:
