// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: coop/drivers/dispatch/v1beta1/driver.proto

package v1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DriverLocation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DriverLocation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DriverLocation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DriverLocationMultiError,
// or nil if none found.
func (m *DriverLocation) ValidateAll() error {
	return m.validate(true)
}

func (m *DriverLocation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDriverId()) < 1 {
		err := DriverLocationValidationError{
			field:  "DriverId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetMostRecentHeartbeat() == nil {
		err := DriverLocationValidationError{
			field:  "MostRecentHeartbeat",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCurrentLocation() == nil {
		err := DriverLocationValidationError{
			field:  "CurrentLocation",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCurrentLocation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DriverLocationValidationError{
					field:  "CurrentLocation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DriverLocationValidationError{
					field:  "CurrentLocation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCurrentLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DriverLocationValidationError{
				field:  "CurrentLocation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DriverLocationMultiError(errors)
	}

	return nil
}

// DriverLocationMultiError is an error wrapping multiple validation errors
// returned by DriverLocation.ValidateAll() if the designated constraints
// aren't met.
type DriverLocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DriverLocationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DriverLocationMultiError) AllErrors() []error { return m }

// DriverLocationValidationError is the validation error returned by
// DriverLocation.Validate if the designated constraints aren't met.
type DriverLocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DriverLocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DriverLocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DriverLocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DriverLocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DriverLocationValidationError) ErrorName() string { return "DriverLocationValidationError" }

// Error satisfies the builtin error interface
func (e DriverLocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDriverLocation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DriverLocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DriverLocationValidationError{}
